Repository SOPT-31th-Seminar-10/Android-Welaaa, pull requests merged in 2022-11, with the labels that each got.

#9 feat: book detail UI & 서버 통신 & 기능 구현 #7 #8
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/welaaa/data/api/ApiClient.kt
  app/src/main/java/com/sopt/welaaa/data/api/BookDetailService.kt
  app/src/main/java/com/sopt/welaaa/data/model/BookDetail.kt
  app/src/main/java/com/sopt/welaaa/data/model/Sample.kt
  app/src/main/java/com/sopt/welaaa/data/repository/SampleRepository.kt
  app/src/main/java/com/sopt/welaaa/data/source/SampleDataSource.kt
  app/src/main/java/com/sopt/welaaa/presentation/bookdetail/adapter/BookDescriptionAdapter.kt
  app/src/main/java/com/sopt/welaaa/presentation/bookdetail/adapter/BookDetailAdapter.kt
  app/src/main/java/com/sopt/welaaa/presentation/bookdetail/adapter/KeywordAdapter.kt
  app/src/main/java/com/sopt/welaaa/presentation/bookdetail/view/BookDetailFragment.kt
  app/src/main/java/com/sopt/welaaa/presentation/bookdetail/viewmodel/BookDetailViewModel.kt
  app/src/main/java/com/sopt/welaaa/presentation/common/ViewModelFactory.kt
  app/src/main/java/com/sopt/welaaa/util/BindingAdapters.kt
  app/src/main/java/com/sopt/welaaa/util/Event.kt
  app/src/main/java/com/sopt/welaaa/util/GlideModule.kt
  app/src/main/java/com/sopt/welaaa/util/ItemDiffCallBack.kt
  app/src/main/res/drawable/background_gray_button.xml
  app/src/main/res/drawable/background_gray_r23.xml
  app/src/main/res/drawable/background_green_button.xml
  app/src/main/res/drawable/background_keyword.xml
  app/src/main/res/drawable/background_stroke_button.xml
  app/src/main/res/drawable/ic_back_round.xml
  app/src/main/res/drawable/ic_book_dummy_01.png
  app/src/main/res/drawable/ic_book_dummy_02.png
  app/src/main/res/drawable/ic_bookdetail_down.xml
  app/src/main/res/drawable/ic_bookdetail_link.xml
  app/src/main/res/drawable/ic_bookdetail_play.xml
  app/src/main/res/drawable/ic_bookdetail_plus.xml
  app/src/main/res/drawable/ic_bookdetail_star.xml
  app/src/main/res/drawable/ic_description_dummy.png
  app/src/main/res/drawable/ic_info_20px.xml
  app/src/main/res/drawable/ic_share_round.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_book_detail.xml
  app/src/main/res/layout/item_book_book_detail.xml
  app/src/main/res/layout/item_description_book_detail.xml
  app/src/main/res/layout/item_keyword_book_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
  settings.gradle
Labels: feat, fix, chore, style, 선웅

#14 [FIX] rearch view
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/welaaa/data/api/SearchRepo.kt
  app/src/main/java/com/sopt/welaaa/data/api/SearchService.kt
  app/src/main/java/com/sopt/welaaa/data/model/ResponseSearchDTO.kt
  app/src/main/java/com/sopt/welaaa/presentation/search/adapter/SearchAdapter.kt
  app/src/main/java/com/sopt/welaaa/presentation/search/view/SearchFragment.kt
  app/src/main/java/com/sopt/welaaa/presentation/search/viewmodel/SearchViewModel.kt
  app/src/main/java/com/sopt/welaaa/util/ItemDiffCallBack.kt
  app/src/main/java/com/sopt/welaaa/util/ItemDiffCallback.kt
  app/src/main/res/drawable-v24/background_search_category_active.png
  app/src/main/res/drawable-v24/background_search_category_inactive.png
  app/src/main/res/drawable-v24/iv_search_1.png
  app/src/main/res/drawable-v24/iv_search_10.png
  app/src/main/res/drawable-v24/iv_search_11.png
  app/src/main/res/drawable-v24/iv_search_12.png
  app/src/main/res/drawable-v24/iv_search_13.png
  app/src/main/res/drawable-v24/iv_search_14.png
  app/src/main/res/drawable-v24/iv_search_15.png
  app/src/main/res/drawable-v24/iv_search_16.png
  app/src/main/res/drawable-v24/iv_search_17.png
  app/src/main/res/drawable-v24/iv_search_18.png
  app/src/main/res/drawable-v24/iv_search_19.png
  app/src/main/res/drawable-v24/iv_search_2.png
  app/src/main/res/drawable-v24/iv_search_3.png
  app/src/main/res/drawable-v24/iv_search_4.png
  app/src/main/res/drawable-v24/iv_search_5.png
  app/src/main/res/drawable-v24/iv_search_6.png
  app/src/main/res/drawable-v24/iv_search_7.png
  app/src/main/res/drawable-v24/iv_search_8.png
  app/src/main/res/drawable-v24/iv_search_9.png
  app/src/main/res/drawable-v24/iv_search_ad_pic.png
  app/src/main/res/drawable-v24/iv_search_category_book.png
  app/src/main/res/drawable/background_search_green.png
  app/src/main/res/drawable/background_search_rectangle.xml
  app/src/main/res/drawable/ic_search_back.xml
  app/src/main/res/drawable/iv_search_rank.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_body_search.xml
Labels: fix, 하정

#19 [REFACTOR] welaaa UI & 기능 refactoring
  app/build.gradle
  app/src/main/java/com/sopt/welaaa/data/model/SearchRepo.kt
  app/src/main/java/com/sopt/welaaa/presentation/bookdetail/view/BookDetailFragment.kt
  app/src/main/java/com/sopt/welaaa/presentation/home/OnBookLikeRecordItemClickListener.kt
  app/src/main/java/com/sopt/welaaa/presentation/home/adapter/BookLikeRecordAdapter.kt
  app/src/main/java/com/sopt/welaaa/presentation/home/view/HomeFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_shelf.xml
  app/src/main/res/layout/item_like_record.xml
Labels: feat, fix, chore, refactor, 선웅
